name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'api'
        type: choice
        options:
          - api
          - functional

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Install Maven
      run: sudo apt-get install maven

    - name: Install Node.js (if needed)
      run: sudo apt-get install nodejs

    - name: Install Maven dependencies
      run: mvn install

    - name: Run API Tests
      if: ${{ github.event.inputs.test_type == 'api' || github.event_name == 'push' }}
      run: mvn test -Papi

    - name: Run Functional Tests
      if: ${{ github.event.inputs.test_type == 'functional' || github.event_name == 'push' }}
      run: mvn test -Pfunctional
